### ISSUE TITLE
Use human-readable schema format

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar-examples#102]
### Category

cedar-example-use-cases, tinytodo

### Describe the expansion you'd like to request

We introduced the human-readable schema format since 3.1. We should update the examples accordingly.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by mwhicks1** [comment]
It also looks like the examples did not get updated for the 3.1 release. Both `tinytodo` and `cedar-rust-hello-world` still reference 3.0 in their `Cargo.toml` files, and no `release/3.1.x` branch has been created. This seems to be a gap in our release runbook.
