### ISSUE TITLE
CI doesn't function for forks

### ISSUE THREAD

**Issue by oflatt** [cedar-policy/cedar-examples#144]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

cedar-example-use-cases

### Describe the bug

Currently, the CI for cedar-examples fails for forks.
See this example run: https://github.com/cedar-policy/cedar-examples/actions/runs/9371870708/job/25802115924?pr=142
AFAICT, this is because it tries to fetch from the main repo instead of the fork.
This is blocking two of my branches (though we can also just give me permissions for this repo).

### Expected behavior

I would expect CI to succeed for branches on forks.

### Reproduction steps

1. Fork this repository.
2. Push a branch.
3. Ci fails

**Comment by john-h-kastner-aws** [comment]
See #90. We had some other issue with builds from forks previously

**Comment by andrewmwells-amazon** [comment]
This seems to be working for forks on my personal GH account:
https://github.com/cedar-policy/cedar-examples/pull/146
https://github.com/cedar-policy/cedar-examples/pull/147

**Comment by andrewmwells-amazon** [comment]
Hopefully fixed with https://github.com/cedar-policy/cedar-examples/pull/149

**Comment by andrewmwells-amazon** [comment]
https://github.com/cedar-policy/cedar-examples/pull/149
