### ISSUE TITLE
Slack Group Invite: Join Cedar Policy Language

### ISSUE THREAD

**Issue by mrpackethead** [cedar-policy/cedar-examples#46]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

cedar-example-use-cases

### Describe the bug

HI, how can I get an invite to the slack channel.

### Expected behavior

....

### Reproduction steps

....

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

**Comment by aaronjeline** [comment]
Here's the link directly for you, to save you a step: https://communityinviter.com/apps/cedar-policy/cedar-policy-language
