### ISSUE TITLE
Is there an option to autogenerate cedarschema from Smithy?

### ISSUE THREAD

**Issue by NukaCody** [cedar-policy/cedar-examples#57]
### Category

tinytodo

### Describe the expansion you'd like to request

It seems like Smithy's resource and operations might be possible to generate a schema from them

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by andrewmwells-amazon** [comment]
I'm not sure why this would be tiny-todo specific (and hence why it belongs in `cedar-examples`)? I'll close for now, but feel free to reopen if you think it makes sense.
