### ISSUE TITLE
Add release/VER branches to this repository

### ISSUE THREAD

**Issue by mwhicks1** [cedar-policy/cedar-examples#60]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

cedar-example-use-cases, cedar-java-hello-world, cear-rust-hello-world, tinytodo

### Describe the bug

There should be a `release/XXX` branch for the examples that tracks the `release/XXX` branches in the [cedar-policy/cedar](https://github.com/cedar-policy/cedar) repository, so that we have examples that track with the various releases. This is important to do because the examples are not stored in their own crates.

### Expected behavior

Each release on should have branch tags on this repository.

### Reproduction steps

N/A

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

**Comment by khieta** [comment]
Resolved for v2.4.x by #68. We will maintain release branches for each minor version going forward.

Since we follow semver, we could get away with maintaining a release branch for every major release, but it makes CI a little easier to have branch names match between `cedar` and `cedar-examples`.
