### ISSUE TITLE
Update tinytodo to reflect changes in https://github.com/cedar-policy/cedar/pull/588

### ISSUE THREAD

**Issue by aaronjeline** [cedar-policy/cedar-examples#91]
### Category

tinytodo

### Describe the expansion you'd like to request

https://github.com/cedar-policy/cedar/pull/588 changes the result type of `PolicyId::from_str`, so tinytodo needs to adjust to that.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by john-h-kastner-aws** [comment]
This is done, right?
